### ISSUE TITLE
Integrating Groovy Template Engine

### ISSUE THREAD

**Issue by SingularityA** [malinink/easy-tests#1]
1. Создать список объектов класса User в Controller
2. Создать простой веб-шаблон, представляющий собой таблицу с полями типа "property", "value" (совместимый с Materialize)
3. Передать список объектов во View
4. Используя groovy template engine, сгенерировать html-страницу из шаблона с данными полей объектов списка 
5. Отобразить готовую страницу

**Comment by malinink** [comment]
Да, в итоге:
 - отдельный контроллер, в нем единственный экшен, пусть будет матчить ```/users```
 - во вьюшке groovy код по генерации единственной таблицы(без body и прочей информации) по формату materialize.
