### ISSUE TITLE
Provide mapper tests checker

### ISSUE THREAD

**Issue by vkpankov** [malinink/easy-tests#101]
Реализовать проверку наличия тестов для мапперов
1. Найти все классы мапперов, тесты для них и поля @autowired в этих тестах
2. Заменить @autowired поле в тесте на proxy (или использовать Mockito.spy)
3. Вызвать методы теста с аннотацией @Test.
4. Проверить, что все методы из маппера были вызваны
5. Повторить 2-4 для каждого маппера

**Comment by vkpankov** [comment]
@malinink, вроде все сделал, но
В каждом тесте у нас есть аннотация
`@Sql(executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD, scripts = "classpath:sql/mappersTestData.sql")`

При "искусственном" же вызове тестов она выполняется сразу для всех методов, а не для каждого, и тесты иногда валятся (из-за попыток найти удаленный объект).

Пробовал выполнять наш скрипт так:

>         dataSource = new PooledDataSource();
        dataSource.setDriver(env.getProperty("driver"));
        dataSource.setUrl(env.getProperty("url"));
        dataSource.setUsername(env.getProperty("username"));
        dataSource.setPassword(env.getProperty("password"));

        dataSource.setDefaultAutoCommit(true);

        Resource resource = new ClassPathResource("/sql/mappersTestData.sql" );

        ScriptUtils.executeSqlScript(dataSource.getConnection(), resource);

но тогда тест вообще зависает на этапе 
`INFO org.springframework.jdbc.datasource.init.ScriptUtils - Executing SQL script from class path resource [sql/mappersTestData.sql]`

**Comment by malinink** [comment]
Предлагаю в таком случае сделать 1 метод, который будет деггаться много раз, т.е. создать data provider для теста, который будет возвращать, например интерфейсы мапперов каждый из которых мы захотим проверить. 
Это всё равно не избавит нас от проблемы, т.к. мы прогоним все тесты для одного маппера сразу, без перевыливки базы.

А если у вас уже сделано именно так(ну теоретически должно было быть так сделано), то у меня есть ещё одно интересное предложение:
 - мы знаем семантику запросов
 - find - выборка
 - insert - вставка
 - update - обновление
 - delete - удаление
Можно после получения списка тестов, выполнять сначала те которые содержат find затем update, insert и уже delete, а за ними последуют все остальные.
