### ISSUE TITLE
Provide auth module tests

### ISSUE THREAD

**Issue by malinink** [malinink/easy-tests#114]
Provide tests for common classes:
- AuthUsersService
- SessionLoginStoreHelper
- AuthenticationFailureHandler

Откорректировать сервис, только пользователь со статусом = 3 должен смочь залогиниться.
статус 4 пользователь должен быть задисейблен, остальные статусы - считаем что аккаунт залочен.

**Comment by DoZor-80** [comment]
@malinink
возьму эту задачку

**Comment by DoZor-80** [comment]
@malinink начал делать тест для AuthUsersService, т.е. я должен проверить правильная ли у юзера роль? Откуда брать тестовые данные? Обшарил интернет, более-менее подходящий пример: http://howtodoinjava.com/junit/how-to-unit-test-spring-security-authentication-with-junit/ 
Но пока не могу написать тест, с помощью него.

**Comment by malinink** [comment]
@DoZor-80 Зачем? вам не нужно проверять корректно ли проверяется имеет ли юзер доступ к какому-то методу, вам нужно проверить конкретный класс, в нем - соответственно есть единственный публичный метод, вот его и необходимо проверить.

Да, раз уж пошла такая пьянка, - добавьте испльзование статуса в этот метод
3 - пользователь активен
4 - пользователь отключен и не должен иметь возможность залогиниться.
остальные значения - тоже не должен логиниться.

**Comment by DoZor-80** [comment]
@malinink Может быть, 1 - пользователь активен, 2 - отключен?

**Comment by malinink** [comment]
@DoZor-80 
Посмотрите в form.tpl admin модуля, там уже используются именно те значения, о которых я написал выше.
Исключение бросать не надо, т.к. говорить информацию о том, что такой пользователь у нас есть  не корректно.
