### ISSUE TITLE
Fix gulp to copy docs files properly

### ISSUE THREAD

**Issue by malinink** [malinink/easy-tests#115]
Сейчас при подготовке в сборке в файле настройки gulp происходит копирование файлов из bower в папки docs и public.
А все файлы созданные в папке docs дополнительно - там и остаются.

Необходимо настроить gulp так, чтобы он эти файлы дополнительно копировал в public(в соответствующие папки).

Также было бы неплохо если бы он минифицировал содержимое, и создавал всегда два файла: минифицированный и обычный.

Например jquery.min.js и jquery.js  

Миницицированные файлы должны ледать только в public иерархии.

**Comment by Loriens** [comment]
@malinink Есть вопрос по первой части задания: что конкретно gulp должен копировать в public? Файлы, которые создаются в docs дополнительно?

**Comment by malinink** [comment]
@Loriens Да, сейчас файлы копируются в докс а потом в проект, необходимо скопировать файлы в докс, а потом все файлы из докс - в проект.
Это касается всех 3 папок, js css и fonts

**Comment by Loriens** [comment]
@malinink Возьму эту задачу.
