### ISSUE TITLE
Create TesteeOptions

### ISSUE THREAD

**Issue by DoZor-80** [malinink/easy-tests#121]
Создать класс TesteeOptions:

- withRelations

- saveWithRelations

- deleteWithRelations

Написать тесты.

**Comment by malinink** [comment]
Эту задачу считаем выполненной, НО нам надо связать Quiz и Testee, Предлагаю вынести это в отдельную задачу, связь будет 1:1 хранить будем quiz_id в testees таблице. Ну и соответственно необходимо поддержку этого добра добавить во всю иерархию - с вас как минимум постановка задачи с адекватным описанием, а в идеале вообще сделать эту подзадачу.
