### ISSUE TITLE
Add findBySubject methods

### ISSUE THREAD

**Issue by vkpankov** [malinink/easy-tests#130]
1. Добавить метод findBySubjectId в TopicsMapper
2. Реализовать методы findBySubject в TopicsService
3. Написать тесты на них

**Comment by malinink** [comment]
@vkpankov Викентий, там не только эти методы, но и иерархия вся, т.е. в мапперах, тоже надо их добавлять. Учтите это.

**Comment by malinink** [comment]
@vkpankov кто мерджит, тот и меняет статусы связанного issue, помяйте по образу и подобию
Со слиянием всё верно сообразили.
