### ISSUE TITLE
Add ORM support with JPA and implement Entity class

### ISSUE THREAD

**Issue by vkpankov** [malinink/easy-tests#14]
Реализовать поддержку ORM используя JPA+Hibernate или myBatis
Cоздать Entity класс на основе User
Создать объект этого класса, связать его со структурой БД

Второй исполнитель - @Firkhraag

**Comment by malinink** [comment]
Hibernate это надмножество над JPA, т.е. скажем так, некая реализация, по JPA стандарту, но есть и просто JPA, поэтому исходя из той информации, которой я владею, лучше не подключать хибернейт, т.к. это очень большая прослойка, нам скорее всего будет достаточно простого JPA.

Ещё раз повторюсь, возможно я неправ, и если просто JPA не подключить, то давайте смотреть в сторону myBatis

Также в рамках вашей задачи - создть объект и связать его со структурой бд, если вы научитесь автоматически переносить структуру объектов в бд - будет вобще замечательно.

Все подробности касательно того как использовать JPA давайте писать на отдельной странице в вики.

Измените постановку задачи, и укажите пожалуйста второго исполнителя.

**Comment by vkpankov** [comment]
@malinink ,
Насколько я понял, чистого JPA нет; 
Правда есть Spring Data JPA, или все же лучше myBatis?
Насчет создания объекта - я правильно понял, что нужно создать экземпляр реализованного Entity-класса и связать его с таблицей в БД?

**Comment by malinink** [comment]
@vkpankov 
Да, испольхзуем имеющийся класс пользователя.
Я немного почитал выходит так, что Spring Data JPA это уникальный интерфейс для JPA и ему нужен любой провайдер работающий по JPA, т.е. например хибернейт.

Давайте вы попробуете рабозраться в хибернейтом, но мои ощущения говорят за что-то более простое.

Я создам ветку, из дева, ПР оформляйте в неё, по названию сообразите. Если разобраться в хибернейтом не выйдет, - пробуйте myBatis (ну и под него я тоже ветку создам, чтобы был выбор)

**Comment by vkpankov** [comment]
@malinink , задачу отредактировал. А где создавать сам объект? Реализовать для этого еще один класс?

**Comment by malinink** [comment]
@vkpankov используйте имеющийся класс пользователя, я же вроде бы написал выше.
