### ISSUE TITLE
Create IssuesOptions

### ISSUE THREAD

**Issue by FortyWays** [malinink/easy-tests#142]
Создать IssuesOptions, IssuesOptionsInterface переделать IssueService и сделать все необходимые изменения для Quiz.
+Тесты.
P.S. Прошлую задачу закрыли, а PR к ней я не успел сделать, поэтому делаю новую.

**Comment by malinink** [comment]
@FortyWays В следующий раз просто попросите открыть обратно задачу, я, видимо, по-запарке её закрыл.
