### ISSUE TITLE
Add Quiz relation to Testee

### ISSUE THREAD

**Issue by DoZor-80** [malinink/easy-tests#144]
Связать Quiz и Testee (1:1), добавить quiz_id в testees-таблицу.
Добавить поддержку этой связи во всей иерархии, добавить тесты.

**Comment by DoZor-80** [comment]
@malinink Добавить эту задачку сюда? 
Обновить тест, который убедится, что id появится после сохранения новой модели.

**Comment by malinink** [comment]
@DoZor-80 
Если его нет - то конечно!
Ну и всё чего не хватает по вашим моделям - тоже можно дописать сюда
