### ISSUE TITLE
Create Answer CRUD controller 

### ISSUE THREAD

**Issue by Rezenbekk** [malinink/easy-tests#149]
- Создать *AnswerController* с методами *create*, *read*, *update*, *delete*;
- *AnswerView*
- формы
- валидация

**Comment by Rezenbekk** [comment]
темплейты ещё не накидал, а контролёр, дто и валидатор есть. пулреквест еще не готов кидать, особенно с учётом грядущей переделки #152

**Comment by malinink** [comment]
Предложил бы всеже выливать по частям, пусть будет пустой контроллер, чтобы был PR и был виден процент его готовности

**Comment by Rezenbekk** [comment]
@malinink 

Я накидаю того, в чём уверен, но это один-два файла. У меня пока 50% строчек кода - это комменты с TODO.
