### ISSUE TITLE
Add essential to the project Spring Modules

### ISSUE THREAD

**Issue by FortyWays** [malinink/easy-tests#15]
Изучить модули Spring, определить какие из них могут понадобиться в проекте и описать почему.
Подключить необходимые модули, к проекту.(PR на ветку dev)
@FortyWays: 
- spring-orm
- spring-expression
- spring-core
- spring-context
- spring-beans
- spring-jdbc 
- spring-jms
- spring-oxm
- spring-tx

@Valentin26:

- spring-messaging
- spring-web-reactive 
- spring-websocket
- spring-aspects
- spring-aom
- spring-instrument

**Comment by malinink** [comment]
@FortyWays 
Имя второго участника в студию, и напишите тут же в задаче кому какие модули достались.

**Comment by Valentin26** [comment]
Имя второго участника-Валентин.Я выбрал модуль-категорию Web.AOP

**Comment by malinink** [comment]
Вы как с другой вселенной, используйте ссылки @FortyWays @Valentin26 
Обновите ещё раз описание, и отпишитесь тут.

**Comment by FortyWays** [comment]
@malinink , так?
