### ISSUE TITLE
Provide Point model

### ISSUE THREAD

**Issue by nikitalpopov** [malinink/easy-tests#151]
Модифицировать сущность Point:  

-  Пометить PointInterface как @deprecated  
-  изменить PointEntity (с использованием lombok), PointsMapper (не использовать методы, принимающие объекты), PointsService (использовать только модель)  
-  добавить PointModel, PointModelInterface, PointModelEmpty  
-  исправить/добавить тесты

**Comment by malinink** [comment]
PointService - зачем его удалять? он нам нужен вроде как! Или имеется ввиду переименовать?

**Comment by nikitalpopov** [comment]
@malinink как я понял, PointService теперь будет PointModelService. Поэтому и написал, что удаляем первый и добавляем второй

**Comment by vkpankov** [comment]
@nikitalpopov , имя сервиса так и останется Point**s**Service

**Comment by nikitalpopov** [comment]
@vkpankov а, окей

**Comment by vkpankov** [comment]
Сервис? Нет, он же нам нужен будет
А @deprecated помечается то, что устарело и не должно больше использоваться

**Comment by nikitalpopov** [comment]
@malinink @vkpankov перепутал. Пишу про сервис, думаю об интерфейсе

**Comment by vkpankov** [comment]
@nikitalpopov ,  PointInterface? Его да, нужно пометить @deprecated
