### ISSUE TITLE
Add an additional field to Answer

### ISSUE THREAD

**Issue by Rezenbekk** [malinink/easy-tests#152]
Добавить поле порядкового номера ответа везде, куда нужно (практически все классы, feelsbadman)

поле *serialNumber*

~~Как его назвать? Варианты:~~

- ~~*priority*~~
- ~~*priorityNumber*~~
- ~~*order*~~

**Comment by Rezenbekk** [comment]
@malinink

**Comment by malinink** [comment]
@Rezenbekk Предлагаю serialNumber что скажете?
order хорош, но в связи с наличием такого ключевого слова в SQL у нас возможны проблемы, предлагаю не использовать его.

Если да - обновите описание, и отпишитесь, если нет предлагаю продолжить дискуссию тут

**Comment by Rezenbekk** [comment]
Да, *serialNumber* звучит хорошо.

**Comment by Rezenbekk** [comment]
Готово, пулреквест висит.
