### ISSUE TITLE
Support testing

### ISSUE THREAD

**Issue by DoZor-80** [malinink/easy-tests#16]
Разобраться, как тестировать проект вручную с помощью команд из консоли
Написать тест для класса User
Изменить README.md, оформить PR.

**Comment by malinink** [comment]
@DoZor-80 
Написать тест для класса User!  (убедится что класс создается и устанавливаемые поля через конструктор можно забрать через геттеры)

Дополните описание.

**Comment by DoZor-80** [comment]
@malinink 
Я должен добавить в зависимости JUnit, а потом использовать команду mvn install -Dtest=[UserTest], которая запускает только один тест?

**Comment by malinink** [comment]
@DoZor-80 Не уверен, если без этого совсем никак - то видимо да. Но я бы поискал варианты решения через консоль мавена.
Найти команды для запуска тестирования - да, причем в идеале как отдельного теста, тестов в папке, так и вообще вех тестов.
