### ISSUE TITLE
Finish the Solution

### ISSUE THREAD

**Issue by Loriens** [malinink/easy-tests#161]
- Добавить в сервис метод для сохранения списка Solutions
- Реализовать SolutionServiceInterface
- Реализовать SolutionOptions и интерфейс
- Добавить методы с SolutionOptions в сервис
- Дописать на это всё тесты

Остальное из раздела сущностей, мапперов и моделей уже реализовано.

**Comment by malinink** [comment]
@Loriens 
Когда оформите PR, перенесите пожалуйста список с чекбоксами в него, чтобы я видел процесс готовности. Оформляйте PR как будет готово хотябы что-то.
