### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by Rezenbekk** [malinink/easy-tests#17]
1) Нужно включить отслеживание репозитория на https://travis-ci.org (я могу включить только для своих репозиториев)
2) Создать, настроить и добавить в репозиторий файл .travis.yml
3) После первого пуша всё должно заработать!

**Comment by malinink** [comment]
ДаЮ создаёте у себя отдельную тестовую ветку, там всё настраиваете тестите проверяете, и тоговый результат вносите уже в ветку созданную по стандартным правилам из дева, в дев соотвественно.
