### ISSUE TITLE
Fix Points hiererchy tests

### ISSUE THREAD

**Issue by malinink** [malinink/easy-tests#184]
Fix all ignored tests

**Comment by malinink** [comment]
@nikitalpopov В идеале бы конечно вам поглядеть на тесты, очень много упало и необходимо разобраться что именно не так, сможете? 
Конкретно проблемы с PointsOptionsTest и PointsServiceTest

**Comment by nikitalpopov** [comment]
@malinink в понедельник сдаю последний зачёт и готов заняться

**Comment by malinink** [comment]
@nikitalpopov 
Хорошо, жду в любом случае каких-то комментариев от вас.

**Comment by nikitalpopov** [comment]
К сожалению, не очень получалось выделить время, только сейчас смог посмотреть код
После всех мерджей PointsOptions пришлось привести в нормальный вид, исправил методы saveWithRelations и deleteWithRelations, но тесты все равно валятся.
И основная проблема связана с сеттерами, на следующий код:
```
final PointModelInterface pointModel = Mockito.mock(PointModelInterface.class);
final QuizModelInterface quizModel = Mockito.mock(QuizModelInterface.class);
pointModel.setQuiz(quizModel);
Assert.assertEquals(quizModel, pointModel.getQuiz());
```
получаю:
```
$ java.lang.AssertionError: 
$ Expected :Mock for QuizModelInterface, hashCode: 507575219
$ Actual   :null
```
Как исправить пока не очень представляю
