### ISSUE TITLE
Showcase Thymeleaf Template Engine

### ISSUE THREAD

**Issue by FortyWays** [malinink/easy-tests#2]
1) Создать список объектов класса Student в контроллере
2) Создать веб-шаблон в виде таблицы, выводящую значения полей объектов
3) Передать список объектов во View
4) Сгенерировать страницу из шаблона с данными списка, с помощью Thymeleaf Template Engine
5) Отобразить страницу

**Comment by malinink** [comment]
url cтраницы с таблицей - ```/users```
