### ISSUE TITLE
Improve code coverage for TopicsOptions.java

### ISSUE THREAD

**Issue by Yarik2308** [malinink/easy-tests#203]
Need to improve coverage to 100%

- [x] testWithRelationsOnSingleModel
- [x] testWithRelationsOnNull
- [x] testWithRelationsOnModelsList
- [x] testSaveWithRelations
- [x] testDeleteWithRelations
- [x] testWithSubject
- [x] testWithQuestions
- [x] testSaveDeleteWithUser
- [x] Деление Тестов на проверку SetQuestions и SetSubject.

https://github.com/malinink/easy-tests/pull/213

**Comment by malinink** [comment]
That class is not member of core models. Choose another one.

**Comment by Yarik2308** [comment]
@malinink Я не уверен, но по моему в данном файле в функции deleteWithRelations() ошибка. Вместо save должны стоять delete.
