### ISSUE TITLE
Fix ignoring of properties in QuestionModelTest

### ISSUE THREAD

**Issue by RisaMagpie** [malinink/easy-tests#280]
- [ ] fix ignore of "questionType"
- [ ] fix ignore of "topic"
- [ ] fix ignore of "answers"

**Comment by malinink** [comment]
@RisaMagpie do you look at my comments in PR about models?
Above ones - already fixed.

**Comment by RisaMagpie** [comment]
Sorry, I don't understand some of your comments and I forgot that you have fixed my model test.
--
Sincerlely, Sorokina S. (308 group) воскресенье, 11 марта 2018г., 22:29 +04:00 от malinink  notifications@github.com :
