### ISSUE TITLE
Find the module for quick compile

### ISSUE THREAD

**Issue by VanilaBear** [malinink/easy-tests#3]
Найти и изучить инструкцию к Spring, которая позволит вносить изменения в проект, не требуя при этом его пересборки. Достаточно обновить страницу в браузере, чтобы посмотреть изменения.

**Comment by malinink** [comment]
@VanilaBear 
Всёже надо найти модуль спринга, который позволит этого добиться. Ну и понять как использовать представляемую им функциональность, т.е. само по себе ничег обновляться конечно не будет.

От вас  ребуется коммит и некий комментарий, - набор действий на стороне пользователя, чтобы можно было увидеть обновленный проект в браузере.

Комментарий по поводу действий - добавьте в README.md
