### ISSUE TITLE
Create a base template std

### ISSUE THREAD

**Issue by vkpankov** [malinink/easy-tests#31]
Создать базовый шаблон с header и footer

**Comment by vkpankov** [comment]
Задач на всех не хватило, можно ли делать эту вдвоем?

**Comment by malinink** [comment]
Здравствуйте, задач на 8 человек, я рассчитываю что эти 8 человек и будут их делать.
Если есть те, кто не был но хотят что-то поделать у меня есть ещё задачи - пусть наишут.

**Comment by Valentin26** [comment]
а если не совсем понимаешь что происходит и что конкретно нужно пока что?и как правильно делать)а вдвоем делая одну задачу будет проще понять

**Comment by malinink** [comment]
@Valentin26 
Ну тогда потратьте время, разберитесь, и сделайте то, что нужно. У меня есть стойкое ощущение что @SingularityA и @Loriens знают что надо делать.
Если у вас непонимание того, что мы делаем, или что надо сделать - задавайте пожалуйста вопросы на паре.
