### ISSUE TITLE
Add Issue Mapper/Model/Controller/ControllerTest

### ISSUE THREAD

**Issue by Yarik2308** [malinink/easy-tests#327]
https://github.com/malinink/easy-tests/pull/328

**Comment by malinink** [comment]
Please  Add in separate task controller/test/mapper and model.
After merge - you could take actions.

**Comment by Yarik2308** [comment]
@malinik 1 PR for mapper and model? Or 1 for mapper and 1 for model?

**Comment by malinink** [comment]
@Yarik2308 Remove list method realization and add controller test class, each method realization in separate PR.

**Comment by Yarik2308** [comment]
@malinink Done
