### ISSUE TITLE
Refactor TopicOptionsTest

### ISSUE THREAD

**Issue by Yarik2308** [malinink/easy-tests#329]
https://github.com/malinink/easy-tests/pull/330

**Comment by malinink** [comment]
As far as I know there is some unrefactored code in topics service. Could you first look into service please?

**Comment by Yarik2308** [comment]
@malinink  as I can see @Ielay has already refactored service.

**Comment by malinink** [comment]
@Yarik2308 It's my fault I mixed up with testees Service, could you make tests for that service first?

**Comment by Yarik2308** [comment]
@malinik I have already done it. 
https://github.com/malinink/easy-tests/pull/262
LUL

**Comment by Yarik2308** [comment]
@malinink I have already done it.
https://github.com/malinink/easy-tests/pull/262
LUL.

**Comment by Yarik2308** [comment]
@malinink  as I can see here
https://docs.google.com/spreadsheets/u/0/d/1NQ4RVm8K0HnwstB8_d60fT5-1CCrIm-YCXDw7tlHxgE/htmlview
U ask me to do ISTopicPriority?

**Comment by Yarik2308** [comment]
@malinink In file TesteesServices not painted. But I think it done. Check pls.
