### ISSUE TITLE
Create the Topic entity

### ISSUE THREAD

**Issue by Loriens** [malinink/easy-tests#44]
Создание класса Topic.

**Поля класса:**
* id;
* name;
* questions;

**Методы класса:**
* getId;
* getName;
* setName;
* getQuestions;
* setQuestions;

**Mapper:**
- find
- findAll
- insert
- update
- delete

**Service:**
- find
- findAll
- save
- delete

**Comment by Loriens** [comment]
@malinink Добавил названия методов для маппера и сервиса.

**Comment by malinink** [comment]
@Loriens 
Тестировать все кроме методов касающихся сущностей.
Про AddQuestion мысль хорошая, но пока что сделайте обычные get set и на этом остановитесь.
