### ISSUE TITLE
Create Subject entity

### ISSUE THREAD

**Issue by vkpankov** [malinink/easy-tests#45]
Создать:

**Subject:** 
- id 
- name 
- topics
- user_id
// поля из IssueStandard

**SubjectsMapper:**
- find
- findAll 
- insert 
- update 
- delete

**SubjectsService:**
 - find
 - findAll
 - save
 - delete

 А также тесты для них

**Comment by malinink** [comment]
@vkpankov 
Скооперируйтесь с @SingularityA ваши классы должны быть взаимосвязаны.
Предлагаю сделать лбо общий базовый класс, либо вообще Issue унаследовать от IssueStandard.

Подсправил имена методов, не забудьте что в бд UnderscoreCase а в моделях CamelCase.

**Comment by malinink** [comment]
@vkpankov 
ешё подправил метод create в маппере, теперь он будет именоваться insert, ориентируйтесь по user классам.

**Comment by vkpankov** [comment]
@malinink , добавил поле topics
