### ISSUE TITLE
Create Point entity

### ISSUE THREAD

**Issue by nikitalpopov** [malinink/easy-tests#48]
**Point** class

**Entity**:
-  id (Integer)
-  type (String)
-  text (String)
-  quiz (Quiz)
-  solutions (List of Solution)

**Mapper**:
-  find
-  findAll
-  insert
-  update
-  delete

**Service**:
-  find
-  findAll
-  save
-  delete

**Comment by malinink** [comment]
@nikitalpopov 
У вас в сущности то id шников не будет, id - будут в бд, а в сущностях будут объекты.
