### ISSUE TITLE
Layout of web app with Groovy

### ISSUE THREAD

**Issue by nikitalpopov** [malinink/easy-tests#5]
Задание №7
Рассмотреть реализацию layout'ов на Groovy.
Практически:
• отключить текущий шаблонизатор
• реализовать пример layout для нашего приложения с помощью Groovy
• сделать PR в `groovy-template-engine`

**Comment by malinink** [comment]
@nikitalpopov 
Задача состоит не в этом!
Задача не теоретическая а практическая, необходимо подключить шаблонизатор(отключить текущий), и реализовать на новом шаблонизаторе рабочий layout. Глубокое понимание всех преимуществ наличия дayout в рамках этой задачи нас не интересует. 
Но пример использования в любом view нас интересует также и он должен присутствовать в коммитах.
Не забыдьте в описании добавить информацию о том в какую ветку мы дедаем PR.

По итогу: обновите описание задачи.
