### ISSUE TITLE
Create Subject entity

### ISSUE THREAD

**Issue by DoZor-80** [malinink/easy-tests#62]
Создать класс **Subject:**

- **id**
- **name**
- **topics**
- **userId**
- **issue_standard_Id**

SubjectMapper:

- **find**
- **findAll**
- **findByUser**
- **insert**
- **update**
- **delete**

SubjectService:

- **find**
- **findAll**
- **findByUser**
- **save**
- **delete**

**Comment by vkpankov** [comment]
@DoZor-80, уже было: https://github.com/malinink/easy-tests/issues/45
