### ISSUE TITLE
Create Testee entity

### ISSUE THREAD

**Issue by DoZor-80** [malinink/easy-tests#63]
Создать класс **Testee**:

- id
- firstName
- lastName
- surname
- group

TesteeMapper:

- find
- findAll
- insert
- update
- delete

TesteeService:

- find
- findAll
- save
- delete

**Comment by DoZor-80** [comment]
@malinink

**Comment by malinink** [comment]
@DoZor-80 Давайте добавим группу и на этом остановимся.

**Comment by DoZor-80** [comment]
@malinink какой будет тип у поля group: integer или varchar?

**Comment by malinink** [comment]
integer
