### ISSUE TITLE
Provide Subject model

### ISSUE THREAD

**Issue by vkpankov** [malinink/easy-tests#68]
**Модифицировать сущность Subject:**
 - Использовать Lombok в POJO сущности. Удалить интерфейс. 
 - Не использовать в маппере методы, принимающие объекты 
 - Реализовать SubjectModel, SubjectModelInterface, EmptyModel
 - В сервисе использовать только модель (через интерфейс)
 - Написать тесты

**Comment by malinink** [comment]
В иделе то бы конечно расписать!
