### ISSUE TITLE
Modify Answer-related classes

### ISSUE THREAD

**Issue by Rezenbekk** [malinink/easy-tests#81]
- Удалить класс *Answer*
- Добавить класс *AnswerEntity*
- Пометить *AnswerInterface* как Deprecated
- Реализовать *AnswerModel*, *AnswerModelInterface*, *AnswerEmptyModel*
- Модифицировать маппер и сервис в соответствии с новым *AnswerEntity*
- Внедрить геттеры и сеттеры с помощью Lombok
- Переписать существующие тесты и добавить новые для вышеописанных классов

**Comment by malinink** [comment]
Описание где?
Почему issue создается когда _уже_ готово решение?!

**Comment by Rezenbekk** [comment]
@malinink 
Добавил описание. 
Виноват, должен был добавить Issue намного раньше.
