### ISSUE TITLE
Create SubjectOptions

### ISSUE THREAD

**Issue by vkpankov** [malinink/easy-tests#85]
1. **Реализовать методы:**
     - withTopics
     - withUser
     - withIssueStandard
     - setTopicsService
     - setUsersService
     - setIssueStandardService
     - withRelations
     - saveWithRelations
     - deleteWithRelations

2. Написать тесты
3. Добавить setId в SubjectsService.save и протестировать

**Comment by malinink** [comment]
@vkpankov 
Учитывайте пожалуйста, что я могу немного поменять концепт в плане названий методов я про (find/save/delete withOptons)
Также обратите внимание что методы with - fluent setters т.е. this возвращают.

**Comment by malinink** [comment]
@vkpankov 
Немного изменил названия методов в Options, поглядите в моём [PR](https://github.com/malinink/easy-tests/pull/87). Думаю это последний вариант.
