### ISSUE TITLE
Create IssueOptions

### ISSUE THREAD

**Issue by FortyWays** [malinink/easy-tests#86]
Реализовать класс и соответсвующий интерфейс с методами:

- withQuizzes
- setIssuesService
- SetQuizzesService
- withRelations
- saveWithRelations
- deleteWithRelations

И написать тесты.

**Comment by malinink** [comment]
@FortyWays 
Немного изменил названия методов в Options, поглядите в моём [PR](https://github.com/malinink/easy-tests/pull/87). Думаю это последний вариант.
