### ISSUE TITLE
Create IssueStandardOptions

### ISSUE THREAD

**Issue by SingularityA** [malinink/easy-tests#89]
Создать интерфейс и класс, реализовать методы:
- withTopicPriorities
- withQuestionTypeOptions
- withSubject
- setTopicPrioritiesService
- setQuestionTypeOptionsService
- setSubjectsService
- withRelations
- saveWithRelations
- deleteWithRelations

Написать на все это тесты.

**Comment by SingularityA** [comment]
@malinink 
with-метод со связью "наверх" все-таки нужно или не нужно реализовывать? 
(в данном случае - withSubject)

**Comment by malinink** [comment]
@SingularityA Да, конечно.
Я также изменил имена методов в Options, поглядите в моём [PR](https://github.com/malinink/easy-tests/pull/87). Думаю это последний вариант.
