### ISSUE TITLE
Create AnswerOptions

### ISSUE THREAD

**Issue by Rezenbekk** [malinink/easy-tests#98]
Создать класс *AnswerOptions* с методами:

- *withQuestion*
- *setQuestionsService*
- *withRelations*
- *saveWithRelations*
- *deleteWithRelations*

Написать тесты.

**Comment by Rezenbekk** [comment]
@malinink 
Для тасков по мелочам, вроде фикса тестов POJO, новый Issue писать или сюда пихать?

**Comment by malinink** [comment]
@Rezenbekk
Допишите задачи и можно легко всё сделать вместе.
Но если основная задача займет у вас много времени, а тесты, к примеру, - дело быстрое и понятное, - то я бы в таком случае сделал на все мелочи отдельную задачу и отдельный PR.
